// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.io.Serializable;
import mx.japs.portal.configuracion.modelo.Modulo;

privileged aspect Modulo_Roo_Serializable {
    
    declare parents: Modulo implements Serializable;
    
    private static final long Modulo.serialVersionUID = 1L;
    
}
