// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.io.Serializable;
import mx.japs.portal.configuracion.modelo.Portal;

privileged aspect Portal_Roo_Serializable {
    
    declare parents: Portal implements Serializable;
    
    private static final long Portal.serialVersionUID = 1L;
    
}
