// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.MenuOpcionDataOnDemand;
import mx.japs.portal.configuracion.modelo.MenuOpcionIntegrationTest;
import mx.japs.portal.configuracion.repositorio.MenuOpcionRepository;
import mx.japs.portal.configuracion.servicio.MenuOpcionService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MenuOpcionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MenuOpcionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MenuOpcionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MenuOpcionIntegrationTest: @Transactional;
    
    @Autowired
    MenuOpcionDataOnDemand MenuOpcionIntegrationTest.dod;
    
    @Autowired
    MenuOpcionService MenuOpcionIntegrationTest.menuOpcionService;
    
    @Autowired
    MenuOpcionRepository MenuOpcionIntegrationTest.menuOpcionRepository;
    
    @Test
    public void MenuOpcionIntegrationTest.testCountAllMenuOpcions() {
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", dod.getRandomMenuOpcion());
        long count = menuOpcionService.countAllMenuOpcions();
        Assert.assertTrue("Counter for 'MenuOpcion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testFindMenuOpcion() {
        MenuOpcion obj = dod.getRandomMenuOpcion();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to provide an identifier", id);
        obj = menuOpcionService.findMenuOpcion(id);
        Assert.assertNotNull("Find method for 'MenuOpcion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MenuOpcion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testFindAllMenuOpcions() {
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", dod.getRandomMenuOpcion());
        long count = menuOpcionService.countAllMenuOpcions();
        Assert.assertTrue("Too expensive to perform a find all test for 'MenuOpcion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MenuOpcion> result = menuOpcionService.findAllMenuOpcions();
        Assert.assertNotNull("Find all method for 'MenuOpcion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MenuOpcion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testFindMenuOpcionEntries() {
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", dod.getRandomMenuOpcion());
        long count = menuOpcionService.countAllMenuOpcions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MenuOpcion> result = menuOpcionService.findMenuOpcionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MenuOpcion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MenuOpcion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testFlush() {
        MenuOpcion obj = dod.getRandomMenuOpcion();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to provide an identifier", id);
        obj = menuOpcionService.findMenuOpcion(id);
        Assert.assertNotNull("Find method for 'MenuOpcion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMenuOpcion(obj);
        Integer currentVersion = obj.getVersion();
        menuOpcionRepository.flush();
        Assert.assertTrue("Version for 'MenuOpcion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testUpdateMenuOpcionUpdate() {
        MenuOpcion obj = dod.getRandomMenuOpcion();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to provide an identifier", id);
        obj = menuOpcionService.findMenuOpcion(id);
        boolean modified =  dod.modifyMenuOpcion(obj);
        Integer currentVersion = obj.getVersion();
        MenuOpcion merged = menuOpcionService.updateMenuOpcion(obj);
        menuOpcionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MenuOpcion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testSaveMenuOpcion() {
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", dod.getRandomMenuOpcion());
        MenuOpcion obj = dod.getNewTransientMenuOpcion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MenuOpcion' identifier to be null", obj.getId());
        try {
            menuOpcionService.saveMenuOpcion(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        menuOpcionRepository.flush();
        Assert.assertNotNull("Expected 'MenuOpcion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MenuOpcionIntegrationTest.testDeleteMenuOpcion() {
        MenuOpcion obj = dod.getRandomMenuOpcion();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuOpcion' failed to provide an identifier", id);
        obj = menuOpcionService.findMenuOpcion(id);
        menuOpcionService.deleteMenuOpcion(obj);
        menuOpcionRepository.flush();
        Assert.assertNull("Failed to remove 'MenuOpcion' with identifier '" + id + "'", menuOpcionService.findMenuOpcion(id));
    }
    
}
