// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.ModuloDataOnDemand;
import mx.japs.portal.configuracion.modelo.ModuloIntegrationTest;
import mx.japs.portal.configuracion.repositorio.ModuloRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ModuloIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ModuloIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ModuloIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ModuloIntegrationTest: @Transactional;
    
    @Autowired
    ModuloDataOnDemand ModuloIntegrationTest.dod;
    
    @Autowired
    ModuloRepository ModuloIntegrationTest.moduloRepository;
    
    @Test
    public void ModuloIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", dod.getRandomModulo());
        long count = moduloRepository.count();
        Assert.assertTrue("Counter for 'Modulo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ModuloIntegrationTest.testFind() {
        Modulo obj = dod.getRandomModulo();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to provide an identifier", id);
        obj = moduloRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Modulo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Modulo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ModuloIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", dod.getRandomModulo());
        long count = moduloRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Modulo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Modulo> result = moduloRepository.findAll();
        Assert.assertNotNull("Find all method for 'Modulo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Modulo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ModuloIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", dod.getRandomModulo());
        long count = moduloRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Modulo> result = moduloRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Modulo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Modulo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ModuloIntegrationTest.testFlush() {
        Modulo obj = dod.getRandomModulo();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to provide an identifier", id);
        obj = moduloRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Modulo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyModulo(obj);
        Integer currentVersion = obj.getVersion();
        moduloRepository.flush();
        Assert.assertTrue("Version for 'Modulo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ModuloIntegrationTest.testSaveUpdate() {
        Modulo obj = dod.getRandomModulo();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to provide an identifier", id);
        obj = moduloRepository.findOne(id);
        boolean modified =  dod.modifyModulo(obj);
        Integer currentVersion = obj.getVersion();
        Modulo merged = moduloRepository.save(obj);
        moduloRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Modulo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ModuloIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", dod.getRandomModulo());
        Modulo obj = dod.getNewTransientModulo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Modulo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Modulo' identifier to be null", obj.getId());
        try {
            moduloRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        moduloRepository.flush();
        Assert.assertNotNull("Expected 'Modulo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ModuloIntegrationTest.testDelete() {
        Modulo obj = dod.getRandomModulo();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Modulo' failed to provide an identifier", id);
        obj = moduloRepository.findOne(id);
        moduloRepository.delete(obj);
        moduloRepository.flush();
        Assert.assertNull("Failed to remove 'Modulo' with identifier '" + id + "'", moduloRepository.findOne(id));
    }
    
}
