// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.Modulo;
import mx.japs.portal.configuracion.modelo.ModuloDataOnDemand;
import mx.japs.portal.configuracion.modelo.PortalDataOnDemand;
import mx.japs.portal.configuracion.repositorio.ModuloRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ModuloDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ModuloDataOnDemand: @Component;
    
    private Random ModuloDataOnDemand.rnd = new SecureRandom();
    
    private List<Modulo> ModuloDataOnDemand.data;
    
    @Autowired
    PortalDataOnDemand ModuloDataOnDemand.portalDataOnDemand;
    
    @Autowired
    ModuloRepository ModuloDataOnDemand.moduloRepository;
    
    public Modulo ModuloDataOnDemand.getNewTransientModulo(int index) {
        Modulo obj = new Modulo();
        setDescripcion(obj, index);
        setNombre(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void ModuloDataOnDemand.setDescripcion(Modulo obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void ModuloDataOnDemand.setNombre(Modulo obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void ModuloDataOnDemand.setUrl(Modulo obj, int index) {
        String url = "url_" + index;
        if (url.length() > 100) {
            url = url.substring(0, 100);
        }
        obj.setUrl(url);
    }
    
    public Modulo ModuloDataOnDemand.getSpecificModulo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Modulo obj = data.get(index);
        Long id = obj.getId();
        return moduloRepository.findOne(id);
    }
    
    public Modulo ModuloDataOnDemand.getRandomModulo() {
        init();
        Modulo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return moduloRepository.findOne(id);
    }
    
    public boolean ModuloDataOnDemand.modifyModulo(Modulo obj) {
        return false;
    }
    
    public void ModuloDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = moduloRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Modulo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Modulo>();
        for (int i = 0; i < 10; i++) {
            Modulo obj = getNewTransientModulo(i);
            try {
                moduloRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            moduloRepository.flush();
            data.add(obj);
        }
    }
    
}
