// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.Operacion;
import mx.japs.portal.configuracion.modelo.OperacionDataOnDemand;
import mx.japs.portal.configuracion.modelo.ServicioDataOnDemand;
import mx.japs.portal.configuracion.repositorio.OperacionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OperacionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OperacionDataOnDemand: @Component;
    
    private Random OperacionDataOnDemand.rnd = new SecureRandom();
    
    private List<Operacion> OperacionDataOnDemand.data;
    
    @Autowired
    ServicioDataOnDemand OperacionDataOnDemand.servicioDataOnDemand;
    
    @Autowired
    OperacionRepository OperacionDataOnDemand.operacionRepository;
    
    public Operacion OperacionDataOnDemand.getNewTransientOperacion(int index) {
        Operacion obj = new Operacion();
        setDescripcion(obj, index);
        setNombre(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void OperacionDataOnDemand.setDescripcion(Operacion obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void OperacionDataOnDemand.setNombre(Operacion obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void OperacionDataOnDemand.setUrl(Operacion obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public Operacion OperacionDataOnDemand.getSpecificOperacion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Operacion obj = data.get(index);
        Long id = obj.getId();
        return operacionRepository.findOne(id);
    }
    
    public Operacion OperacionDataOnDemand.getRandomOperacion() {
        init();
        Operacion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return operacionRepository.findOne(id);
    }
    
    public boolean OperacionDataOnDemand.modifyOperacion(Operacion obj) {
        return false;
    }
    
    public void OperacionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = operacionRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Operacion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Operacion>();
        for (int i = 0; i < 10; i++) {
            Operacion obj = getNewTransientOperacion(i);
            try {
                operacionRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            operacionRepository.flush();
            data.add(obj);
        }
    }
    
}
