// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.OperacionDataOnDemand;
import mx.japs.portal.configuracion.modelo.OperacionIntegrationTest;
import mx.japs.portal.configuracion.repositorio.OperacionRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OperacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OperacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OperacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OperacionIntegrationTest: @Transactional;
    
    @Autowired
    OperacionDataOnDemand OperacionIntegrationTest.dod;
    
    @Autowired
    OperacionRepository OperacionIntegrationTest.operacionRepository;
    
    @Test
    public void OperacionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", dod.getRandomOperacion());
        long count = operacionRepository.count();
        Assert.assertTrue("Counter for 'Operacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OperacionIntegrationTest.testFind() {
        Operacion obj = dod.getRandomOperacion();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to provide an identifier", id);
        obj = operacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Operacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Operacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OperacionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", dod.getRandomOperacion());
        long count = operacionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Operacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Operacion> result = operacionRepository.findAll();
        Assert.assertNotNull("Find all method for 'Operacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Operacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OperacionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", dod.getRandomOperacion());
        long count = operacionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Operacion> result = operacionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Operacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Operacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OperacionIntegrationTest.testFlush() {
        Operacion obj = dod.getRandomOperacion();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to provide an identifier", id);
        obj = operacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Operacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOperacion(obj);
        Integer currentVersion = obj.getVersion();
        operacionRepository.flush();
        Assert.assertTrue("Version for 'Operacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OperacionIntegrationTest.testSaveUpdate() {
        Operacion obj = dod.getRandomOperacion();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to provide an identifier", id);
        obj = operacionRepository.findOne(id);
        boolean modified =  dod.modifyOperacion(obj);
        Integer currentVersion = obj.getVersion();
        Operacion merged = operacionRepository.save(obj);
        operacionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Operacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OperacionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", dod.getRandomOperacion());
        Operacion obj = dod.getNewTransientOperacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Operacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Operacion' identifier to be null", obj.getId());
        try {
            operacionRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        operacionRepository.flush();
        Assert.assertNotNull("Expected 'Operacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OperacionIntegrationTest.testDelete() {
        Operacion obj = dod.getRandomOperacion();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operacion' failed to provide an identifier", id);
        obj = operacionRepository.findOne(id);
        operacionRepository.delete(obj);
        operacionRepository.flush();
        Assert.assertNull("Failed to remove 'Operacion' with identifier '" + id + "'", operacionRepository.findOne(id));
    }
    
}
