// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.ParametroDataOnDemand;
import mx.japs.portal.configuracion.modelo.ParametroIntegrationTest;
import mx.japs.portal.configuracion.repositorio.ParametroRepository;
import mx.japs.portal.configuracion.servicio.ParametroService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParametroIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParametroIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParametroIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParametroIntegrationTest: @Transactional;
    
    @Autowired
    ParametroDataOnDemand ParametroIntegrationTest.dod;
    
    @Autowired
    ParametroService ParametroIntegrationTest.parametroService;
    
    @Autowired
    ParametroRepository ParametroIntegrationTest.parametroRepository;
    
    @Test
    public void ParametroIntegrationTest.testCountAllParametroes() {
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", dod.getRandomParametro());
        long count = parametroService.countAllParametroes();
        Assert.assertTrue("Counter for 'Parametro' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParametroIntegrationTest.testFindParametro() {
        Parametro obj = dod.getRandomParametro();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to provide an identifier", id);
        obj = parametroService.findParametro(id);
        Assert.assertNotNull("Find method for 'Parametro' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Parametro' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParametroIntegrationTest.testFindAllParametroes() {
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", dod.getRandomParametro());
        long count = parametroService.countAllParametroes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Parametro', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Parametro> result = parametroService.findAllParametroes();
        Assert.assertNotNull("Find all method for 'Parametro' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Parametro' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParametroIntegrationTest.testFindParametroEntries() {
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", dod.getRandomParametro());
        long count = parametroService.countAllParametroes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Parametro> result = parametroService.findParametroEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Parametro' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Parametro' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParametroIntegrationTest.testFlush() {
        Parametro obj = dod.getRandomParametro();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to provide an identifier", id);
        obj = parametroService.findParametro(id);
        Assert.assertNotNull("Find method for 'Parametro' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParametro(obj);
        Integer currentVersion = obj.getVersion();
        parametroRepository.flush();
        Assert.assertTrue("Version for 'Parametro' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParametroIntegrationTest.testUpdateParametroUpdate() {
        Parametro obj = dod.getRandomParametro();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to provide an identifier", id);
        obj = parametroService.findParametro(id);
        boolean modified =  dod.modifyParametro(obj);
        Integer currentVersion = obj.getVersion();
        Parametro merged = parametroService.updateParametro(obj);
        parametroRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Parametro' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParametroIntegrationTest.testSaveParametro() {
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", dod.getRandomParametro());
        Parametro obj = dod.getNewTransientParametro(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Parametro' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Parametro' identifier to be null", obj.getId());
        try {
            parametroService.saveParametro(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        parametroRepository.flush();
        Assert.assertNotNull("Expected 'Parametro' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParametroIntegrationTest.testDeleteParametro() {
        Parametro obj = dod.getRandomParametro();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Parametro' failed to provide an identifier", id);
        obj = parametroService.findParametro(id);
        parametroService.deleteParametro(obj);
        parametroRepository.flush();
        Assert.assertNull("Failed to remove 'Parametro' with identifier '" + id + "'", parametroService.findParametro(id));
    }
    
}
