// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import mx.japs.portal.configuracion.modelo.ParametroDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParametroDataOnDemand_Roo_Configurable {
    
    declare @type: ParametroDataOnDemand: @Configurable;
    
}
