// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.PortalDataOnDemand;
import mx.japs.portal.configuracion.modelo.PortalIntegrationTest;
import mx.japs.portal.configuracion.repositorio.PortalRepository;
import mx.japs.portal.configuracion.servicio.PortalService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PortalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PortalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PortalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PortalIntegrationTest: @Transactional;
    
    @Autowired
    PortalDataOnDemand PortalIntegrationTest.dod;
    
    @Autowired
    PortalService PortalIntegrationTest.portalService;
    
    @Autowired
    PortalRepository PortalIntegrationTest.portalRepository;
    
    @Test
    public void PortalIntegrationTest.testCountAllPortals() {
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", dod.getRandomPortal());
        long count = portalService.countAllPortals();
        Assert.assertTrue("Counter for 'Portal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PortalIntegrationTest.testFindPortal() {
        Portal obj = dod.getRandomPortal();
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portal' failed to provide an identifier", id);
        obj = portalService.findPortal(id);
        Assert.assertNotNull("Find method for 'Portal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Portal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PortalIntegrationTest.testFindAllPortals() {
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", dod.getRandomPortal());
        long count = portalService.countAllPortals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Portal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Portal> result = portalService.findAllPortals();
        Assert.assertNotNull("Find all method for 'Portal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Portal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PortalIntegrationTest.testFindPortalEntries() {
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", dod.getRandomPortal());
        long count = portalService.countAllPortals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Portal> result = portalService.findPortalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Portal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Portal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PortalIntegrationTest.testFlush() {
        Portal obj = dod.getRandomPortal();
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portal' failed to provide an identifier", id);
        obj = portalService.findPortal(id);
        Assert.assertNotNull("Find method for 'Portal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPortal(obj);
        Integer currentVersion = obj.getVersion();
        portalRepository.flush();
        Assert.assertTrue("Version for 'Portal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PortalIntegrationTest.testUpdatePortalUpdate() {
        Portal obj = dod.getRandomPortal();
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portal' failed to provide an identifier", id);
        obj = portalService.findPortal(id);
        boolean modified =  dod.modifyPortal(obj);
        Integer currentVersion = obj.getVersion();
        Portal merged = portalService.updatePortal(obj);
        portalRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Portal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PortalIntegrationTest.testSavePortal() {
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", dod.getRandomPortal());
        Portal obj = dod.getNewTransientPortal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Portal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Portal' identifier to be null", obj.getId());
        try {
            portalService.savePortal(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        portalRepository.flush();
        Assert.assertNotNull("Expected 'Portal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PortalIntegrationTest.testDeletePortal() {
        Portal obj = dod.getRandomPortal();
        Assert.assertNotNull("Data on demand for 'Portal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Portal' failed to provide an identifier", id);
        obj = portalService.findPortal(id);
        portalService.deletePortal(obj);
        portalRepository.flush();
        Assert.assertNull("Failed to remove 'Portal' with identifier '" + id + "'", portalService.findPortal(id));
    }
    
}
