// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.ServicioOperacionDataOnDemand;
import mx.japs.portal.configuracion.modelo.ServicioOperacionIntegrationTest;
import mx.japs.portal.configuracion.repositorio.ServicioOperacionRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServicioOperacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServicioOperacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServicioOperacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServicioOperacionIntegrationTest: @Transactional;
    
    @Autowired
    ServicioOperacionDataOnDemand ServicioOperacionIntegrationTest.dod;
    
    @Autowired
    ServicioOperacionRepository ServicioOperacionIntegrationTest.servicioOperacionRepository;
    
    @Test
    public void ServicioOperacionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", dod.getRandomServicioOperacion());
        long count = servicioOperacionRepository.count();
        Assert.assertTrue("Counter for 'ServicioOperacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testFind() {
        ServicioOperacion obj = dod.getRandomServicioOperacion();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to provide an identifier", id);
        obj = servicioOperacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ServicioOperacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServicioOperacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", dod.getRandomServicioOperacion());
        long count = servicioOperacionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServicioOperacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServicioOperacion> result = servicioOperacionRepository.findAll();
        Assert.assertNotNull("Find all method for 'ServicioOperacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServicioOperacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", dod.getRandomServicioOperacion());
        long count = servicioOperacionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServicioOperacion> result = servicioOperacionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ServicioOperacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServicioOperacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testFlush() {
        ServicioOperacion obj = dod.getRandomServicioOperacion();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to provide an identifier", id);
        obj = servicioOperacionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ServicioOperacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServicioOperacion(obj);
        Integer currentVersion = obj.getVersion();
        servicioOperacionRepository.flush();
        Assert.assertTrue("Version for 'ServicioOperacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testSaveUpdate() {
        ServicioOperacion obj = dod.getRandomServicioOperacion();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to provide an identifier", id);
        obj = servicioOperacionRepository.findOne(id);
        boolean modified =  dod.modifyServicioOperacion(obj);
        Integer currentVersion = obj.getVersion();
        ServicioOperacion merged = servicioOperacionRepository.save(obj);
        servicioOperacionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServicioOperacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", dod.getRandomServicioOperacion());
        ServicioOperacion obj = dod.getNewTransientServicioOperacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServicioOperacion' identifier to be null", obj.getId());
        try {
            servicioOperacionRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        servicioOperacionRepository.flush();
        Assert.assertNotNull("Expected 'ServicioOperacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServicioOperacionIntegrationTest.testDelete() {
        ServicioOperacion obj = dod.getRandomServicioOperacion();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServicioOperacion' failed to provide an identifier", id);
        obj = servicioOperacionRepository.findOne(id);
        servicioOperacionRepository.delete(obj);
        servicioOperacionRepository.flush();
        Assert.assertNull("Failed to remove 'ServicioOperacion' with identifier '" + id + "'", servicioOperacionRepository.findOne(id));
    }
    
}
