// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.ServicioDataOnDemand;
import mx.japs.portal.configuracion.modelo.ServicioIntegrationTest;
import mx.japs.portal.configuracion.repositorio.ServicioRepository;
import mx.japs.portal.configuracion.servicio.ServicioService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServicioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServicioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServicioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServicioIntegrationTest: @Transactional;
    
    @Autowired
    ServicioDataOnDemand ServicioIntegrationTest.dod;
    
    @Autowired
    ServicioService ServicioIntegrationTest.servicioService;
    
    @Autowired
    ServicioRepository ServicioIntegrationTest.servicioRepository;
    
    @Test
    public void ServicioIntegrationTest.testCountAllServicios() {
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", dod.getRandomServicio());
        long count = servicioService.countAllServicios();
        Assert.assertTrue("Counter for 'Servicio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServicioIntegrationTest.testFindServicio() {
        Servicio obj = dod.getRandomServicio();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to provide an identifier", id);
        obj = servicioService.findServicio(id);
        Assert.assertNotNull("Find method for 'Servicio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Servicio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServicioIntegrationTest.testFindAllServicios() {
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", dod.getRandomServicio());
        long count = servicioService.countAllServicios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Servicio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Servicio> result = servicioService.findAllServicios();
        Assert.assertNotNull("Find all method for 'Servicio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Servicio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServicioIntegrationTest.testFindServicioEntries() {
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", dod.getRandomServicio());
        long count = servicioService.countAllServicios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Servicio> result = servicioService.findServicioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Servicio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Servicio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServicioIntegrationTest.testFlush() {
        Servicio obj = dod.getRandomServicio();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to provide an identifier", id);
        obj = servicioService.findServicio(id);
        Assert.assertNotNull("Find method for 'Servicio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServicio(obj);
        Integer currentVersion = obj.getVersion();
        servicioRepository.flush();
        Assert.assertTrue("Version for 'Servicio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServicioIntegrationTest.testUpdateServicioUpdate() {
        Servicio obj = dod.getRandomServicio();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to provide an identifier", id);
        obj = servicioService.findServicio(id);
        boolean modified =  dod.modifyServicio(obj);
        Integer currentVersion = obj.getVersion();
        Servicio merged = servicioService.updateServicio(obj);
        servicioRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Servicio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServicioIntegrationTest.testSaveServicio() {
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", dod.getRandomServicio());
        Servicio obj = dod.getNewTransientServicio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Servicio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Servicio' identifier to be null", obj.getId());
        try {
            servicioService.saveServicio(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        servicioRepository.flush();
        Assert.assertNotNull("Expected 'Servicio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServicioIntegrationTest.testDeleteServicio() {
        Servicio obj = dod.getRandomServicio();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Servicio' failed to provide an identifier", id);
        obj = servicioService.findServicio(id);
        servicioService.deleteServicio(obj);
        servicioRepository.flush();
        Assert.assertNull("Failed to remove 'Servicio' with identifier '" + id + "'", servicioService.findServicio(id));
    }
    
}
