// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.japs.portal.configuracion.modelo;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.japs.portal.configuracion.modelo.ServicioDataOnDemand;
import mx.japs.portal.configuracion.modelo.ServicioOperacion;
import mx.japs.portal.configuracion.modelo.ServicioOperacionDataOnDemand;
import mx.japs.portal.configuracion.repositorio.ServicioOperacionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ServicioOperacionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ServicioOperacionDataOnDemand: @Component;
    
    private Random ServicioOperacionDataOnDemand.rnd = new SecureRandom();
    
    private List<ServicioOperacion> ServicioOperacionDataOnDemand.data;
    
    @Autowired
    ServicioDataOnDemand ServicioOperacionDataOnDemand.servicioDataOnDemand;
    
    @Autowired
    ServicioOperacionRepository ServicioOperacionDataOnDemand.servicioOperacionRepository;
    
    public ServicioOperacion ServicioOperacionDataOnDemand.getNewTransientServicioOperacion(int index) {
        ServicioOperacion obj = new ServicioOperacion();
        setDescripcion(obj, index);
        setNombre(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void ServicioOperacionDataOnDemand.setDescripcion(ServicioOperacion obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void ServicioOperacionDataOnDemand.setNombre(ServicioOperacion obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void ServicioOperacionDataOnDemand.setUrl(ServicioOperacion obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public ServicioOperacion ServicioOperacionDataOnDemand.getSpecificServicioOperacion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ServicioOperacion obj = data.get(index);
        Long id = obj.getId();
        return servicioOperacionRepository.findOne(id);
    }
    
    public ServicioOperacion ServicioOperacionDataOnDemand.getRandomServicioOperacion() {
        init();
        ServicioOperacion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return servicioOperacionRepository.findOne(id);
    }
    
    public boolean ServicioOperacionDataOnDemand.modifyServicioOperacion(ServicioOperacion obj) {
        return false;
    }
    
    public void ServicioOperacionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = servicioOperacionRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ServicioOperacion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ServicioOperacion>();
        for (int i = 0; i < 10; i++) {
            ServicioOperacion obj = getNewTransientServicioOperacion(i);
            try {
                servicioOperacionRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            servicioOperacionRepository.flush();
            data.add(obj);
        }
    }
    
}
